### ISSUE TITLE
[1.18.2] Failure to load correctly

### ISSUE THREAD

**Issue by Baggytrousers27** [dadobug1111/DadobugBedrockOres#1]
Dadobug1111's Bedrock Ores (dadobugbedrockores) has failed to load correctly

java.lang.reflect.InvocationTargetException: null

Forge 40.0.12
dadobugbedrockores-1.3.1-forge
architectury-4.1.32

[Crashlog](https://pastebin.com/UUKRF8nU)

**Comment by dadobug1111** [comment]
Just fixed it! Update will be out shortly on curseforge.

**Comment by Baggytrousers27** [comment]
Cheers. ¦ )
