### ISSUE TITLE
Feature: Modular Routers compat

### ISSUE THREAD

**Issue by Raidobw2** [dadobug1111/DadobugBedrockOres#10]
I would like to see if compatibility for Modular Routers can be added. https://www.curseforge.com/minecraft/mc-mods/modular-routers

Currently the breaker module turns the blocks into air

Relayed from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1062 and will shortly report to Modular Routers as well, see below for the linked issue

Thanks for reading my suggestion :)

**Comment by desht** [comment]
The fundamental problem here is that Bedrock Ores relies on `IForgeBlock#onDestroyedByPlayer()` being called, which only occurs as  a result of a `ServerBoundPlayerActionPacket` being received from a client.  This does not happen when a block breaker type mod (like Modular Routers and its Breaker Module) breaks blocks purely server side, so your blocks don't get regenerated.

So this isn't just a Modular Routers compatibility question; it's about playing nice with any server-sided block breaker.

**Comment by dadobug1111** [comment]
rewritten regen has fixed this, works wonderfully!

**Comment by Raidobw2** [comment]
Awesome, much thanks! :D
