### ISSUE TITLE
AOE Mining Tools break bedrock ores

### ISSUE THREAD

**Issue by LandonCalling** [dadobug1111/DadobugBedrockOres#11]
When using a mining tool with an AOE, like the Fluxbore from the Thermal Series, the block that the tool is actively mining will drop an item and not break like usual, but any other bedrock ores in the AOE range will drop an item and break leaving a hole to the void.   Playing in the FTB Plexiglass Mountain modpack.  Forge version 40.1.52.  Mod version 1.3.6

**Comment by dadobug1111** [comment]
This should be fixed now! Reopen if still broken.
