### ISSUE TITLE
AOE Mining Tools Breaking Bedrock Ores - Update

### ISSUE THREAD

**Issue by LandonCalling** [dadobug1111/DadobugBedrockOres#12]
So after the recent update to bedrock ores, it looks like AOE tool mining of bedrock ores is still broken.  Although in a slightly different fashion.  Now when you mine bedrock ores with an AOE mining tool like the fluxbore from the Thermal Series all the bedrock ores break leaving a hole to the void, including the one you are actively looking at.  In the previous issue I posted it was breaking all of the AOE blocks but leaving the block you were actively looking at.  Playing in FTB Plexiglass Mountain version 1.1.1, Forge version 40.1.52, mod version 1.4.0  Previous Issue #11

**Comment by dadobug1111** [comment]
have you re-generated the config and found freshly generated ores? If you use older ores, it may not have the new block entity present. Without the entity present, the ores do not regen.

**Comment by LandonCalling** [comment]
Ahh good to know.  I’ll do that and try again.

**Comment by dadobug1111** [comment]
Yeah, I decided to just find a fix for it. It now will add a block entity if it does not have one when broken, then use that one for regenning the block. 1.4.1 has been released with this fix.
Like last time, if there are still problems, just reopen the issue or create a new one.
