### ISSUE TITLE
Incompatability with Flat Bedrock

### ISSUE THREAD

**Issue by Nevrai** [dadobug1111/DadobugBedrockOres#14]
Bedrock ores don’t generate anywhere when using [Flat Bedrock](https://www.curseforge.com/minecraft/mc-mods/flat-bedrock), which makes the bedrock layer flat, resulting in a single layer of bedrock at Y: −64.

I don’t know why bedrock ores aren’t generating with Flat Bedrock. The bedrock ores generated normally when I removed Flat Bedrock and created a new world.

I love this mod quite a lot, but I also despise the messy vanilla layer of bedrock, and so do many other people considering the popularity of flat-bedrock mods. Is it possible that compat with Flat Bedrock could be added? If so, that would be more than wonderful!

### Versions
* **Minecraft:** 1.18.2
* **Forge:** 40.1.80 (latest for 1.18.2)
* **Dadobug1111’s Bedrock Ores:** 1.4.3-forge (latest for 1.18.2)

**Comment by dadobug1111** [comment]
that should not happen. I will look into fixing it!

**Comment by DeleteMetaInf** [comment]
Thank you! Hopefully you will find a solition.

**Comment by Nevrai** [comment]
Thank you! Hopefully you will find a solution.

**Comment by Nevrai** [comment]
My modpack is pretty close to being able to be tested, although one issue that stands in the way is this incompatability, so I hope you’ll be able to fix it soon. It would be much appreciated!

**Comment by dadobug1111** [comment]
one temporary solution would be to add a datapack that generates the ores.

**Comment by dadobug1111** [comment]
I have found the issue. The "find a higher bedrock to start on" bit of code was starting too high. After going down 5 blocks, It would be just above the bedrock. I have lowered this, and have confirmed it to work.

**Comment by Nevrai** [comment]
Thank you for the Flat Bedrock fix and Powah! compatability. You rock! Or shall I say, you bedrock. (Sorry.)

**Comment by dadobug1111** [comment]
puns are always allowed, and even encouraged, here!
