### ISSUE TITLE
RFTools Builder does not seem to be working in 1.4.4, even with loop on

### ISSUE THREAD

**Issue by Raidobw2** [dadobug1111/DadobugBedrockOres#17]
Hi! I've loaded the mod in 1.4.4 on Minecraft 1.18.2 to test some auto miners with the ores, and it looks like the RFTools Builder might be broken.
Create and Modular Routers work well, but I cannot get the builder to work.

Here is a video attached showing it:

https://user-images.githubusercontent.com/17010632/197955282-744e58ac-336f-4cbf-9cfc-ba7791ad0793.mp4

I am using the default generated config after a reinstall of a small amount of auto miner mods alongside Bedrock Ores.

Here are all the mods I have installed, with Forge 40.1.84:

```
architectury-4.10.86-forge.jar
cloth-config-6.4.90-forge.jar
create-1.18.2-0.5.0.e.jar
dadobugbedrockores-1.4.4-forge.jar
flywheel-forge-1.18.2-0.6.5.jar
mcjtylib-1.18-6.0.17.jar
modular-routers-1.18.2-9.1.1-93.jar
rftoolsbase-1.18-3.0.11.jar
rftoolsbuilder-1.18-4.0.16.jar
```

Also, the builder is set to loop infinitely while it has a redstone signal, given by the lever.

Thanks for looking into it in advance!

**Comment by dadobug1111** [comment]
https://user-images.githubusercontent.com/33583954/197986426-589027cf-c79d-474e-a057-f372360b2c1e.mp4

I cannot seem to replicate the issue. I did add createaddition-1.18.2-20220914a.jar for the creative generator. Otherwise, the modset is an exact clone of yours. I used curseforge to set it up, and did no configuration.

**Comment by Raidobw2** [comment]
Apologies, I deleted the test instance and made a new one with the same modset and now it works. I have absolutely no idea what made it not work the first time. I've launched the new test instance consistently 2 times and the ores can be mined properly by the builder.
Sorry for the confusion and thank you for your help

**Comment by Raidobw2** [comment]
Hey, just wanted to mention a quick update since I found out what happened. The rftools builder default config had the tile entities disabled for quarrying. I had forgotten about it and I didn't notice the change to the bedrock ores at first. That explains why I was confused about it not working at first, since i had removed content but kept the same saves, which had that rftools builder config!

After updating that config and letting Bedrock Ores regenerate the configs too, everything works again. It had been a while since I had your mod updated, and the new update really brings fresh air with more ore compat, new enchants, new regen code and extended configurability of the mod. It's very useful for us pack devs. Thanks a lot for those amazing features!

**Comment by dadobug1111** [comment]
Glad to see you enjoying it. If you have any ores you want added, just tell me. Have fun!
