### ISSUE TITLE
Crash shortly after joining world

### ISSUE THREAD

**Issue by Raidobw2** [dadobug1111/DadobugBedrockOres#19]
Relayed from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2010

Versions:
`dadobugbedrockores-1.4.4-forge.jar`
On Forge 40.1.84 for MC 1.18.2

User's quote
> Crashes when the world is loaded from menu. Usually loads for a few seconds and then crashes completely. I have an automated set up mining a few ores and a little logistics train running around picking it up and dropping it off. Nothing is directly interacting with soulstone bedrock ores, but there are plenty around the area. This started happening on the 15th in 1.2.2, I rolled it back to the most recent save, no luck, same thing. Updated to 1.2.3 today and same thing. Crash report is from today ver 1.2.3. Not familiar with github or bug reporting, if you need more info or logs let me know. :)

Crash log: https://paste.feed-the-beast.com/view/cf9cf396

I'll ask them for a few steps to help debugging the issue, but I wanted to get the crash on here to get your opinion if this could happen, or if you needed more info. Thanks in advance!

P.S. Not much changed in FTB Plexiglass Mountain 1.2.2, but if you want to check the changelog in any case it's available under Versions here, it's small https://www.feed-the-beast.com/modpacks/96-ftb-plexiglass-mountain

**Comment by dadobug1111** [comment]
Somehow an air block has been set as the keepstate for the regenerative block entity. That should not happen, but I should be able to throw together a fix to prevent it from crashing if/when it does

**Comment by dadobug1111** [comment]
Just updated! Curseforge should approve it soon.

**Comment by Raidobw2** [comment]
Sorry for replying late, been busy with school... thanks a lot for coding a fix! I've asked the user that had the issue to test with the newer version of the mod, I will get back to you quickly🙂

**Comment by dadobug1111** [comment]
The User has stated that the problem is fixed. You are welcome!

**Comment by Raidobw2** [comment]
Yes, I only saw their reply just now... Thank you very much for your availability and the quick fixes as always, you're awesome! 😎
