### ISSUE TITLE
[Enhancement] Immersive Engineering ores compatibility 

### ISSUE THREAD

**Issue by Royal-Jelly** [dadobug1111/DadobugBedrockOres#2]
IE adds the following ores:
- Bauxite Ore (Aluminium).
- Lead Ore.
- Silver Ore.
- Nickel Ore.

Its not a deal breaker, just a fun thing I thought I'd suggest.

**Comment by dadobug1111** [comment]
Nice idea, I will start on it after bed!

**Comment by dadobug1111** [comment]
Just finished! Sorry for the wait, lost track of time...
I am going to try adding gregtech ores, then update curseforge.
