### ISSUE TITLE
[1.19.2 Forge] "Infinite" option does not properly work with fluids

### ISSUE THREAD

**Issue by Geekerandy** [dadobug1111/DadobugBedrockOres#21]
So currently I wanted to limit water and lava to a finite amount in my modpack, with these config options listed below:
![image](https://user-images.githubusercontent.com/14936715/203991507-55ce2569-c0ad-49b5-9bf2-ca9406e683b6.png)

However, when attempting to extract the fluid, there is essentially infinite fluid inside the bedrock. 
The reason for knowing this other than actually extracting more than the MaxDurability value is that when mined a  _single_ time, it reverts back to it's source block or back to bedrock, depending on config option of course.

**Comment by dadobug1111** [comment]
It seems like I forgot to make the fluid ore self-destruct when out of durability. I am busy today, but I should be able to throw together something this weekend to fix it.

**Comment by dadobug1111** [comment]
Sorry for the wait. Fixed in latest release 1.5.3
