### ISSUE TITLE
Crash on Forge server

### ISSUE THREAD

**Issue by Raidobw2** [dadobug1111/DadobugBedrockOres#5]
Hello! It looks like the mod is crashing on loading servers trying to access a client class. I don't know much about it, but java.awt.color enable you to do the same thing as the current one that's crashing.

Mod: `dadobugbedrockores-1.3.4-forge`
Forge: `40.1.20`
Minecraft: `1.18.2`
https://paste.feed-the-beast.com/view/9bba06d4

Looking forward to continue using the mod, let me know if this is something you'd want to fix and thanks!

**Comment by dadobug1111** [comment]
oh... I think I know what is causing that. Lemme just fix that real quick.

**Comment by dadobug1111** [comment]
Ok, just uploaded the update. this update _should_ fix this issue. dev environment is running server just fine.

**Comment by Raidobw2** [comment]
Hello, thanks for the answer! I only got to test that today, and I can confirm that the mod now fully works on servers. Thanks a bunch for the quick support and have a nice day!
