### ISSUE TITLE
Feature Request: Create mod drilling

### ISSUE THREAD

**Issue by zehmaria** [dadobug1111/DadobugBedrockOres#6]
Hi, I would like to ask if it is possible to make the bedrock ores work with Create's Mechanical Drill [Both forge and fabric]. Right now, the blocks just drop one and disappear, like the normal ores. 

If you consider this out of your scope, please close the issue. 

Thank you for your time and the mod. Cheers.

**Comment by dadobug1111** [comment]
Ok, I will look into fixing that, and adding create ores while I am at it!

**Comment by dadobug1111** [comment]
I cannot seem to fix this myself, but I have submitted an issue to the create team with a suggestion on how to fix it.

The ores, however, I can get right to work on!

**Comment by Warhand** [comment]
Came here to request this same feature, so can confirm it would be an appreciated addition, and I'm glad to see its already being looked into.

**Comment by theodoorhughes** [comment]
Also modular routers, and applied energistics.

**Comment by desht** [comment]
See #10 for exactly why various block breaker don't work well with this mod.

**Comment by dadobug1111** [comment]
Ok, I have been completely rewriting the methods behind block regen. The new format puts the block back via block-entity whenever onStateReplaced is called, or when the state changes and the block gets ticked. This should fix ALL block-breakers. I will be releasing it soon™ (when it is finished). It is looking promising so far!

**Comment by dadobug1111** [comment]
It works! create drills work wonderfully! Modular Routers work as well. applied energistics breaks it but does not drop anything _yet_. Closing issue, yay!
