### ISSUE TITLE
Ars Nouveau & RFTools can break the bedrock ores

### ISSUE THREAD

**Issue by Raidobw2** [dadobug1111/DadobugBedrockOres#7]
If you use a break+amplify spell from Ars Nouveau for mining harder materials, the bedrock ores are destroyed, opening a path to the void. If you use a RFTools Builder (RFTools Utility mod) with a (clearing) quarry card, it always break the bedrock ores completely and somehow you get the resources.

Not sure if this is something you can fix easily, but thought I'd report anyways

`dadobugbedrockores-1.3.5-forge.jar` on Forge `40.1.20` for Minecraft `1.18.2`

**Comment by 5ully** [comment]
This is also the case for Create mechanical drill, using same version of bedrock ores, forge and minecraft version as above.

**Comment by dadobug1111** [comment]
I am unable to fix these issues myself, but I have put issues on all of these mods issue trackers. If/when they add in compatibility, I will push an update to curseforge and comment here.

**Comment by dadobug1111** [comment]
Ars Nouveau & RFTools have been fixed.
RFTools self-patched
Ars Nouveau accepted pull request
Create is tracked in #6 
Closing issue, yay!

**Comment by Raidobw2** [comment]
Thanks! :D
