### ISSUE TITLE
Feature request: Misc. ore support.

### ISSUE THREAD

**Issue by Warhand** [dadobug1111/DadobugBedrockOres#8]
I had a few requests when it comes to ore compatibility, I'll share them in groups, sorted by dimension and mod.

Alternatively, some type of framework for players/packdevs to add their own ores would be good as well.

## **Undergarden mod:**
**Undergarden dimension:**
- Cloggrum
- froststeel
- Utherium
- Diamond
- Iron
- Coal
- Gold

## **Beyond Earth Mod:**
**Moon dimension:**
- Desh
- Iron
- Ice
- Cheese

**Mars Dimension:**
- Ostrum
- Iron
- Diamond
- Ice

**Venus Dimension:**

- Coal
- Gold
- Diamond
- Calorite

**Glacio Dimension:**

- Coal
- Copper
- Iron
- Lapis Lazuli
- Ice

## **Malum Mod:**
**Overworld**

- Soulstone
- Brilliance (Experience, could replace XP founts if Malum is installed)

**Nether:**

- Blazing quartz

## **FTB Industrial Contraptions:**
**Overworld:**

- Tin Ore
- Lead Ore
- Aluminum Ore
- Silver Ore
- Iridium

**Comment by dadobug1111** [comment]
*Scribbles on notepad* Don't mind me, just preparing for the final 1.18.2 update(s)

**Comment by dadobug1111** [comment]
added by request #13
