### ISSUE TITLE
Feature Request: Industrial Foregoing Block Breaker

### ISSUE THREAD

**Issue by scottsumrall** [dadobug1111/DadobugBedrockOres#9]
Unsure if this is fixable on your end but the industrial foregoing block breaker machine seems to be completely unable to break/harvest the bedrock ores added from this mod.

**Comment by dadobug1111** [comment]
The block breaker they use simulates a diamond pickaxe, which is too weak to break the ores by default. I have submitted an issue for that on their github.

**Comment by Ironcanon** [comment]
Mentioned the wrong issue by mistake, my bad.

**Comment by dadobug1111** [comment]
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1282 - has fixed the issue! Tested it myself.
